# Site settings
title: Haizhou
email: higocn@163.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.chenhaizhou.tk" # the base hostname & protocol for your site
twitter_username: chenhaizhou
github_username:  chenhaizhou
facebook_usrname: 
qq: 309973094
skype_username: chen.haizhou1
pygments: true
# Build settings
markdown: kramdown
paginate: 5
tags_path : /tags.html
timezone: China/Beijing

enable_disqus: true
disqus_shortname: chenhaizhou
