# Site settings
title: Haizhou Chen
email: higocn@163.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chenhaizhou
github_username:  chenhaizhou

# Build settings
markdown: kramdown
paginate: 5
tags_path : /tags.html
timezone: China/Beijing
